# General Settings
TOPOLOGY_NAME: "media_topology"
topology.workers: 2
topology.debug: false

topology.message.timeout.secs: 3600
topology.max.spout.pending: 128
#topology.executor.receive.buffer.size: 32
#topology.executor.send.buffer.size: 32
#topology.transfer.buffer.size: 32
#topology.backpressure.enable: true

# Media topology specific
MEDIATOPOLOGY_FILE_SERVICE_URL: "https://test-cloud.europeana.eu/api"
MEDIATOPOLOGY_FILE_SERVICE_USER: 
MEDIATOPOLOGY_FILE_SERVICE_PASSWORD: 
MEDIATOPOLOGY_DATASET_PROVIDER: "mms_prov"
MEDIATOPOLOGY_DATASET_ID: "mms_set"

MEDIATOPOLOGY_FILE_TRANSFER_PORT: 4401

MEDIATOPOLOGY_PARALLEL_HINT_DOWNLOAD: 10
MEDIATOPOLOGY_PARALLEL_HINT_PROCESSING: 10

#MEDIATOPOLOGY_DATASET_EMIT_LIMIT: 10
#MEDIATOPOLOGY_RESULT_PERSIST: false

#Zookeeper
INPUT_ZOOKEEPER_ADDRESS: "10.10.30.36,10.10.30.37,10.10.30.38"

# Cassandra
CASSANDRA_HOSTS: "cassandra-01.man.poznan.pl,cassandra-02.man.poznan.pl,cassandra-03.man.poznan.pl,cassandra-04.man.poznan.pl,cassandra-05.man.poznan.pl,cassandra-06.man.poznan.pl"
CASSANDRA_PORT: 9042
CASSANDRA_KEYSPACE_NAME: "test_ecloud_dps_v1"
CASSANDRA_USERNAME: 
CASSANDRA_PASSWORD: 
#
# Spout/Bolt Parallelism
NOTIFICATION_BOLT_PARALLEL: 1
#
# Storm Parallelism
NOTIFICATION_BOLT_NUMBER_OF_TASKS: 1


