tomcat:
  build: tomcat
  ports:
    - "8080:8080"
  links:
    - cassandra:cassandra
    - swift:swift
    - zookeeper:zookeeper
    - kafka:kafka

cassandra:
  build: cassandra
  ports:
    - "9042:9042"
    - "9160:9160"

swift:
  build: docker-swift-onlyone
  ports:
    - "8888:8888"
  volumes:
    - /srv

zookeeper:
  image: wurstmeister/zookeeper:3.4.6
  ports:
    - "2182:2181"

kafka:
  image: akrystian/kafka-docker
  links:
   - zookeeper:zookeeper
  environment:
    KAFKA_CREATE_TOPICS: "topic:1:1"
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $$1}'"
  ports:
   - "9092:9092"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock

nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "3773"
    - "3772"
    - "6627"
  links:
    - zookeeper:zookeeper

supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
    - cassandra:cassandra
    - tomcat:tomcat

ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
  links:
    - nimbus:nimbus
    - zookeeper:zookeeper
